-- ========================================================
-- BRACKETZZ V2 - SUPABASE DATABASE SCHEMA
-- Jalankan skrip ini di SQL Editor pada Dashboard Supabase
-- ========================================================

-- 1. Tabel Pemain (Players)
CREATE TABLE IF NOT EXISTS public.players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    photo TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabel Turnamen (Tournaments)
CREATE TABLE IF NOT EXISTS public.tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sport TEXT NOT NULL,
    format TEXT NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    created_at TEXT NOT NULL
);

-- 3. Tabel Peserta Turnamen (Participants)
CREATE TABLE IF NOT EXISTS public.participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT REFERENCES public.tournaments(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    photo TEXT
);

-- 4. Tabel Pertandingan (Matches)
CREATE TABLE IF NOT EXISTS public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT REFERENCES public.tournaments(id) ON DELETE CASCADE,
    round INTEGER NOT NULL,
    participant1_id BIGINT REFERENCES public.participants(id) ON DELETE SET NULL,
    participant2_id BIGINT REFERENCES public.participants(id) ON DELETE SET NULL,
    score1 INTEGER DEFAULT 0 NOT NULL,
    score2 INTEGER DEFAULT 0 NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL,
    next_match_id BIGINT
);

-- Aktifkan Row Level Security (RLS) dengan akses publik (Anonymous Read & Write)
-- Cocok untuk proyek demo / kompetisi internal tanpa login rumit
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- Policy untuk Players
CREATE POLICY "Akses penuh publik untuk players" ON public.players
    FOR ALL USING (true) WITH CHECK (true);

-- Policy untuk Tournaments
CREATE POLICY "Akses penuh publik untuk tournaments" ON public.tournaments
    FOR ALL USING (true) WITH CHECK (true);

-- Policy untuk Participants
CREATE POLICY "Akses penuh publik untuk participants" ON public.participants
    FOR ALL USING (true) WITH CHECK (true);

-- Policy untuk Matches
CREATE POLICY "Akses penuh publik untuk matches" ON public.matches
    FOR ALL USING (true) WITH CHECK (true);

-- Aktifkan Supabase Realtime untuk tabel matches dan tournaments
ALTER PUBLICATION supabase_realtime ADD TABLE public.matches;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tournaments;
